### ISSUE TITLE
COMPROPAGO TABLES NOT FOUND

### ISSUE THREAD

**Issue by dabodude** [compropago/plugin-woocommerce#10]
Después de actualizar a esta versión, el checkout produce este error al finalizar el pedido con compropago.

WooCommerce 2.5

**Comment by elkusko** [comment]
Al parece no se te crearon las tablas cuando se instalo el plugin, podrías  desactivar/activar el plugin desde el listado de Wordpress, para verificar si te notifica algún error de creación de las tablas de ComproPago. 

Saludos

**Comment by dabodude** [comment]
Eso era! Gracias!

Aprovecho para avisarte que el link debajo de "Si llego buscando el archivo de instalación para su tienda" no funciona.

Saludos!
