### ISSUE TITLE
Status por default On-Hold? - Webhook - Log

### ISSUE THREAD

**Issue by dabodude** [compropago/plugin-woocommerce#11]
Hola,

Los pedidos ahora se marcan de inmediato como on-hold en lugar de pending payment al momento de crear una nueva orden.

Aparentemente mi webhook no funciona para comprobar si debería cambiar de estado después "No se puede inicializar WordPress"

No parece que se guarde el log para revisar el problema.

**Comment by elkusko** [comment]
Gracias por tus valiosas retro alimentación, con respecto a este issue:

Si son marcadas on-hold y unos segundos después (normalmente) el webhook cambia el status a pending payment.  Esto con la intención de poder identificar fallos en el webhook como es el caso.

El error  "No se puede inicializar WordPress" en el webhook puede suceder por un par de cuestiones  al evaluar la constante WP_SITEURL .

- No están definidas ambas urls en los settings de wordpress; Settings->General para WordPress Address (WP_HOMEURL) y  Site Address (WP_SITEURL) 
- El archivo que la define no esta siendo auto cargado por wp-load.php ( posible detalle de versión de WP) 

Si tu caso es la primera opción te pediría actualizar y probar nuevamente, sino, En los settings del checkout te aparece la ruta del webhook?  algún error o en blanco?. te solicitaría me compartas tus  versiones de Wordpress, Woocommerce y PHP. para identificar el issue.

Del manejo de logs efectivamente está versión no está utilizando el WC_Logger por el momento,  tomo nota para reincorporar en la  próxima versión .

**Comment by dabodude** [comment]
Seguro!

Ya entiendo lo del webhook aunque genera posibles confusiones porque a pesar de que el pedido aún no ha sido pagado, se crean los correos de pedido nuevo para el cliente y para el comercio, supongo que simplemente puedo cambiar el código para mi tienda.

Si aparece la ruta para el webhook en el admin del plugin.

WP: 4.4.1
WC: 2.5
PHP: 5.4.13

Gracias!

**Comment by elkusko** [comment]
La situación de los status si sería por el momento para tu tienda,  está considerado para el periodo de releases en Febrero, una serie modificación del lado del administrador para desde ahí definir los comportamientos de debug, status, inventario al momento de la orden y webhook.

Con la configuración del URL para WP_SITEURL se soluciono la respuesta del webhook?   ya que no me ha sido posible replicar el error en los ambientes con los que dispongo . para darte una solución más certera.  dado caso se puede eliminar esa validación del webhook para no afectar la operación de tu tienda.

**Comment by dabodude** [comment]
La configuración del site url esta bien. Me extraña mucho que no lea el webhook. Si tienes chance, compartimos pantalla

**Comment by elkusko** [comment]
claro. me podrías mandar una invitación por Skype a: iptigo.rolando

**Comment by elkusko** [comment]
Se suprimió la validación de la constante de WP WP_SITEURL, por problemas de compatibilidad entre versiones de WP. 
Se coloco código para compatibilidad de respuesta webhook con API 1.0
El código se ha cambiado en el master de github y se publicara en la próxima  versión de patch

El manejo de Status e Inventario quedo custom a la tienda.  ( por confirmar comportamiento WC en inventario a edo. procesando en lugar de completed)

**Comment by dabodude** [comment]
Confirmo que el status de pending a processing se está llevando a cabo correctamente gracias al webhook. Sin embargo no se están reduciendo las existencias en este cambio de status.

Recomiendo usar:
https://docs.woothemes.com/wc-apidocs/source-class-WC_Abstract_Order.html#2337-2396

**Comment by elkusko** [comment]
opciones a recepción de pago de acuerdo a flujo de tienda:

```php
$order->update_status('processing', __( 'ComproPago - Payment Confirmed', 'compropago' ));
$order->reduce_order_stock();
```

ó

```php
$order->payment_complete();
```
