### ISSUE TITLE
No se puede traducir "Your payment order at ComproPago is ready"

### ISSUE THREAD

**Issue by dabodude** [compropago/plugin-woocommerce#12]
No parece que la frase "Your payment order at ComproPago is ready" tome su traducción asignada

**Comment by elkusko** [comment]
el resto de las traducciones te aparecen de manera correcta, que idioma estas utilizando?.

**Comment by dabodude** [comment]
Si el resto funciona bien, sólo esa frase. es_MX

**Comment by elkusko** [comment]
Parece error de compilación, ya que si se encuentra correcta en .po , revisare la situación y se aplicara el cambio en el siguiente patch

**Comment by elkusko** [comment]
se re compilaron los archivos, y se realiza fix manual. El detalle es de ejecución de woocommerce en process_payment al idioma base del plugin (en). se invertira en futura versión a (es)
