### ISSUE TITLE
Status Refunded?

### ISSUE THREAD

**Issue by dabodude** [compropago/plugin-woocommerce#13]
No he tenido oportunidad de probar el escenario donde se marque un pago como reembolsado desde ComproPago pero en el plugin anterior ya cambiaba el estado del pedido de woocommerce a "Refunded" y por lo que alcancé a leer en el código parece que ya no existe un cambio de status para esta situación.

Muy buen trabajo de todos modos! Sólo ayudando con un poco de retroalimentación.

**Comment by elkusko** [comment]
no se esta contemplando el status Refunded,  se realizara la corrección en el siguiente patch de versión.  por el momento la operación regresa al estado de default On-Hold.

Gracias por la retroalimentación y felicitacion .

Saludos

**Comment by elkusko** [comment]
En lo que está lista la versión de patch. se puede realizar  el siguiente cambio en el webhook para tener el comportamiento de la versión anterior.

```php
case 'COMPROPAGO_DECLINED':
				$order->update_status('cancelled', __( 'ComproPago - Declined', 'compropago' ));
			break;
```
por

```php
case 'COMPROPAGO_DECLINED':
				$order->update_status('refunded', __( 'ComproPago - Declined', 'compropago' ));
			break;
```

**Comment by elkusko** [comment]
se eleva request a nivel de API
