### ISSUE TITLE
ComproPago Unexpected http code error

### ISSUE THREAD

**Issue by andresadanmx** [compropago/plugin-woocommerce#14]
Tengo la versión de Wordpress 4.4.2 y woocommerce 2.5.2 he instalado la última versión de compropago, sin embargo al ingresar las keys de prueba y guardar me sale el siguiente mensaje en la caja que está abajo de "enable/disable": ComproPago Unexpected http code error: http://prntscr.com/a4irzl

En la parte frontal en el checkout no se muestra el logotipo de compropago aunque este se haya activado en el admin con "show logos", en su lugar se muestra el mensaje: This payment method is not available: http://prntscr.com/a4is9o

El webhook está configurado en ambos lados de la siguiente manera: http://www.misitioweb.com/wp-content/plugins/compropago/webhook.php

La versión php que tengo es la 5.4.

**Comment by rolandolucio** [comment]
Buena tarde, para descartar un par de situaciones podría Activar/Desactivar el Modo Activo ( Live Mode). y al guardar compartirme si le sale alguna otra alerta y/o se repite la misma.

**Comment by andresadanmx** [comment]
He desactivado/activado el "Live Mode" y la alerta es la misma.

**Comment by rolandolucio** [comment]
Podría verificar que sus llaves, el modo de su tienda y de su cuenta se encuentren en modo activo. 

Para ser mas asertivo si puede agregarme por Skype para que me comparta su pantalla y  revisar detalles particulares de su cuenta, mi skype es:  iptigo.rolando

O si lo prefiere por el ticket de soporte o con nuestra operadora de chat proporcionarme un número de contacto.

saludos

**Comment by andresadanmx** [comment]
No es un error del plugin.

Para que funcione la cuenta abierta en Compropago esta debe estar en modo activo, de otro modo dará lugar a que el plugin en Woocommerce no funcione completamente.

Rolando muchas gracias por la ayuda.
