### ISSUE TITLE
Fatal Error (en 4.2.1.0 y 4.3.0.0) 

### ISSUE THREAD

**Issue by vicius23** [compropago/plugin-woocommerce#57]
Hola,

Desde hace 24h aproximadamente se muestra el siguiente error en el panel de ajustes de ComproPago (y no deja hacer pagos en la web tampoco, da error "ComproPago is not valid"):

Fatal error: Uncaught exception 'Exception' in /home/admin/public_html/****/wp-content/plugins/compropago/vendor/compropago/php-sdk/CompropagoSdk/Tools/Http.php:149 Stack trace: #0 /home/admin/public_html/****/wp-content/plugins/compropago/vendor/compropago/php-sdk/CompropagoSdk/Tools/Request.php(53): CompropagoSdk\Tools\Http->executeRequest() #1 /home/admin/public_html/****/wp-content/plugins/compropago/vendor/compropago/php-sdk/CompropagoSdk/Service.php(55): CompropagoSdk\Tools\Request::get('http://api.comp...') #2 /home/admin/public_html/****/wp-content/plugins/compropago/compropago.php(68): CompropagoSdk\Service->listDefaultProviders() #3 [internal function]: compropago_config_page('') #4 /home/admin/public_html/****/wp-includes/class-wp-hook.php(286): call_user_func_array('compropago_conf...', Array) #5 /home/admin/public_html/****/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array) #6 /home/admin/public_ in /home/admin/public_html/****/wp-content/plugins/compropago/vendor/compropago/php-sdk/CompropagoSdk/Tools/Http.php on line 149

Deduje que quizás era por no estar actualizado a la 4.3.0.0, pero tras hacer una instalación limpia de la 4.3.0.0 el problema persiste. Hasta la fecha he podido usar el plugin sin problemas.

¿Alguna idea de qué ha podido pasar y cómo se puede solventar? 
PHP Version: | 5.6.34
WordPress Version: | 4.9.4
Server Software: | Apache

**Comment by vicius23** [comment]
Parece que el sistema ahora funciona correctamente, entiendo que quizás hubo algún problema de conexión con ComproPago, pero parece estar todo bien ya. Gracias!

**Comment by danteay** [comment]
Efectivamente, sufrimos una caida en la API pero ya fue reestablecida. Lamentamos las molestias que ocaciono este error. Seguiremos monitoreando el API durante el dia de hoy para evitar mas problemas de este tipo.
