### ISSUE TITLE
Response: el payload esparado es diferente en 4.3.0.0

### ISSUE THREAD

**Issue by vicius23** [compropago/plugin-woocommerce#58]
Desde la actualización a la versión 4.3.0.0 observo dos situaciones relacionadas:

1) Al probar el webhook en el panel, se obtiene esta respuesta:
Existen errores en su URL, consulte la documentación de los estandares de webhooks aquí 
Response: el payload esparado es diferente.
Timeout 3573ms
Status code 200
Respuesta
{"status":"pending"}
<img width="569" alt="captura de pantalla 2018-03-30 a las 17 01 55" src="https://user-images.githubusercontent.com/868694/38142309-1b148348-343c-11e8-9ce7-32f42466e469.png">

La URL que se autoconfigura es: https://www.*******.com/wp-json/compropago/webhook

2) Imagino que debido a ello, no se actualiza un pedido cuando se completa el pago, teniendo que cambiar el estado del pedido manualmente.

He probado a borrar los webhooks (se conservaba el antiguo) y dejar que se creara de nuevo, así como a borrar completamente el plugin y habilitarlo de nuevo, manteniéndose el mismo problema.

Se agradece cualquier orientación para recuperar el funcionamiento normal, si se necesita colaboración por supuesto encantado de prestarla.

Funcionando actualmente en PHP 5.6.34, Woo 3.3.4, WP 4.9.4.

Un saludo.

**Comment by danteay** [comment]
Efectivamente @vicius23, existia un error en el webhook que no permitia ejecutar  correctamente el webhook.

Ya fue corregido en el release [4.3.0.1](https://github.com/compropago/plugin-woocommerce/releases/tag/4.3.0.1).

**Comment by vicius23** [comment]
Perfecto, actualizo. Gracias por la rapidez Eduardo.
