### ISSUE TITLE
Todos los pedidos se reciben con estado En Espera (4.3.0.1)

### ISSUE THREAD

**Issue by vicius23** [compropago/plugin-woocommerce#61]
En la versión 4.3.0.1, sin tomar en cuenta la configuración en el panel de la opción "Estatus inicial de la orden", todos los pedidos se ponen con el estado "En Espera", mientras que en anteriores versiones se mantenía el estado configurado.

<img width="251" alt="captura de pantalla 2018-03-30 a las 18 18 10" src="https://user-images.githubusercontent.com/868694/38144840-c3c263b6-3446-11e8-8711-1614a8c015e4.png">
<img width="404" alt="captura de pantalla 2018-03-30 a las 18 18 39" src="https://user-images.githubusercontent.com/868694/38144846-ca883982-3446-11e8-92b3-92e882ee6e23.png">

**Comment by danteay** [comment]
Corregido en [4.3.0.2](https://github.com/compropago/plugin-woocommerce/releases/tag/4.3.0.2)
