### ISSUE TITLE
Temporalmente fuera de servicio

### ISSUE THREAD

**Issue by liberaiphoneimei** [compropago/plugin-woocommerce#74]
Desde hace aproximadamente 48h (puede que más) el plugin de WooCommerce está devolviendo en la opción Pago en Efectivo el error mencionado en el título. La opción SPEI si carga y se ejecuta correctamente.

<img width="225" alt="captura de pantalla 2018-09-28 a las 16 06 54" src="https://user-images.githubusercontent.com/868694/46218115-258d2680-c344-11e8-93aa-c2744dcf9ea7.png">

**Comment by liberaiphoneimei** [comment]
Hola,

Realmente no ha vuelto a funcionar, pero hemos detectado donde está el fallo.

En los pagos de hasta 1500 Pesos sale sin problema para hacer el pedido y escoger establecimiento. En los pagos que superan los 1600-1700 Pesos aprox, sale el error “ Temporalmente fuera de servicio”, como si hubiera algún tipo de límite. 

¿Podéis revisarlo?

Gracias.

**Comment by IGE3K** [comment]
> Buenas tardes,
> 
> El problema persiste con los pagos que superan la cantidad indicada, ¿sabéis algo al respecto? Os lo agradecería.
> 
> Un saludo.

Que tal buenas tardes, tengo el mismo problema ¿lo pudiste resolver liberaiphoneimei ?

Pensé que era la versión del plugin ya hice un Downgrade, sigue igual y ahora no encuentro versiones anteriores para probar 

Gracias

**Comment by danteay** [comment]
Mmm este error me suna a que el API no esta aplicando el filtro de precios adecuado a los proveedores y regresa todos sin distincion, por eso al escoger un proveedor que no soporta el monto se produce el fallo @IGE3K @liberaiphoneimei

**Comment by IGE3K** [comment]
Listo amigo wladix la envíe a tu e-mail waldix86@gmail.com
Gracias !

**Comment by IGE3K** [comment]
@liberaiphoneimei Me diste la pista exacta para salir de este problema, es un plugin de Currency @waldix @danteay desactivado el plugin ya aparecen las opciones. veré si se mejora actualizándolo si no tendré que vivir sin el

**Comment by IGE3K** [comment]
@liberaiphoneimei @waldix @danteay Mil gracias, ya esta trabajando nuevamente actualice el plug de currency y es compatible

**Comment by dabodude** [comment]
Es el de WooCommerce Currency Converter?
