### ISSUE TITLE
Webhook no funciona en 5.0

### ISSUE THREAD

**Issue by liberaiphoneimei** [compropago/plugin-woocommerce#76]
Hola,

En la versión 5.0 ha dejado de funcionar la conexión con el Webhook y no se actualiza WooCommerce con el pedido recibido, debiendo hacerse a mano cada vez.

Saludos.

**Comment by JoseBSX** [comment]
Se genero nuevo release con la corrección, [Versión 5.0.0.1](https://github.com/compropago/plugin-woocommerce/releases/tag/5.0.0.1)
