### ISSUE TITLE
... failed to open stream: No such file or directory...

### ISSUE THREAD

**Issue by misaelnieto** [compropago/plugin-woocommerce#82]
* WordPress 5.1.1
* PHP: 7
* WooCommerce 3.5.7
* Hosting: WebFaction

Instalé el plugin siguiendo las [instrucciones de instalación](http://demo.compropago.com/plugins/woocommerce). Al activar el plugin aparece el siguiente mensaje de error:

```php
Warning: require_once(/home/myuser/webapps/tienda/wp-content/plugins/plugin-woocommerce-master/vendor/autoload.php): failed to open stream: No such file or directory in /home/myuser/webapps/tienda/wp-content/plugins/plugin-woocommerce-master/compropago.php on line 15

Fatal error: require_once(): Failed opening required '/home/myuser/webapps/tienda/wp-content/plugins/plugin-woocommerce-master/vendor/autoload.php' (include_path='.:/usr/local/share/pear72') in /home/myuser/webapps/tienda/wp-content/plugins/plugin-woocommerce-master/compropago.php on line 15
```
Hay que instalar composer para que funcione el plugin?

**Comment by danteay** [comment]
Este error pasa porque se intentó una instalación directamente de la rama máster de este repositorio. Debe descargar el archivo comprobado.zip de el último release
